detectors:
  ControlParameter:
    enabled: false
  FeatureEnvy:
    enabled: false
  IrresponsibleModule:
    enabled: false
  UtilityFunction:
    enabled: false
  NestedIterators:
    max_allowed_nesting: 2
  TooManyStatements:
    max_statements: 10
exclude_paths:
  - db/migrate
