---
require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
  - db/schema.rb
  - bin/*
  - locale/*

Metrics/AbcSize:
  Max: 20
  Exclude:
  - db/migrate/*

Metrics/BlockLength:
  Max: 30
  Exclude:
  - spec/**/*
  - config/routes.rb

Metrics/ClassLength:
  Max: 120

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
  Exclude:
  - db/migrate/*

Metrics/ModuleLength:
  Max: 120

RSpec/EmptyExampleGroup:
  Exclude:
  - spec/integration/internal/**/*
  - spec/policies/**/*

RSpec/ScatteredSetup:
  Exclude:
    - spec/policies/**/*

RSpec/ExampleLength:
  Max: 11

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
  - locale/custom_locales.rb
  - db/migrate/*

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true
