---
require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
  - db/schema.rb
  - bin/*
  - locale/*

  NewCops: enable

Metrics/AbcSize:
  Max: 22
  Exclude:
  - db/migrate/*

Metrics/BlockLength:
  Max: 30
  Exclude:
  - spec/**/*
  - config/routes.rb

Metrics/ClassLength:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
  Exclude:
  - db/migrate/*

Metrics/ModuleLength:
  Max: 120

RSpec/EmptyExampleGroup:
  Exclude:
  - spec/integration/internal/**/*
  - spec/policies/**/*

RSpec/ScatteredSetup:
  Exclude:
    - spec/policies/**/*

RSpec/ExampleLength:
  Max: 11

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
  - locale/custom_locales.rb
  - db/migrate/*
