FROM ruby:2.6.5-alpine

ENV PROJECT_ROOT=/app \
WD_INSTALL_DIR=/home/webdrivers
WORKDIR $PROJECT_ROOT

RUN apk update && \
apk add -u --no-cache --progress \
tzdata \
build-base \
postgresql-dev postgresql-client openssh git make \
chromium chromium-chromedriver nodejs-current imagemagick npm cmake less graphviz

COPY Gemfile* $PROJECT_ROOT/

RUN gem install bundler -v 2.0.2
RUN bundle check || BUNDLE_FORCE_RUBY_PLATFORM=1 bundle install --jobs 4 --retry 4
# Temporal solution to work with chromedriver
RUN mkdir /home/webdrivers && ln -s /usr/bin/chromedriver /home/webdrivers/chromedriver

RUN npm config set unsafe-perm true && npm install -g yarn
COPY package.json yarn.lock $PROJECT_ROOT/
RUN yarn install
